services:
  mind-estoque-database:
    image: mysql:9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estoque
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password