services:
  server:
    build:
      context: .
      target: production
    entrypoint: wait-for database:3306 -t 40 -- npm run start
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=mysql://root:root@database:3306/estoque
    depends_on:
      - database

  database:
    image: mysql:9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estoque
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always